version: "3.8"
services:
  web:
    build:
      context: .
      target: development
      dockerfile: ./docker/local/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go_cache:/root/.cache/go-build # go buildのキャッシュを永続化
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # dbサービスが「healthy」（健全）状態になるまで起動
    restart:
      on-failure # サービスが失敗した場合、再起動します。
      # - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web Interface

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass Passw0rd
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=Passw0rd

volumes:
  go_cache:
  db_data:
